name: Build Custom ROM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout ROM Source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Java Development Kit 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Initialize ROM Manifest
      run: |
        repo init -u git://github.com/Just-CAF/platform_manifest.git -b q
        git clone https://github.com/whatawurst/android_device_sony_poplar.git -b lineage-17.1 device/sony/poplar
        git clone https://github.com/whatawurst/android_vendor_sony_poplar.git -b lineage-17.1 vendor/sony/poplar
        git clone https://github.com/whatawurst/android_kernel_sony_msm8998.git -b lineage-17.1 kernel/sony/msm8998

    - name: Sync ROM Source
      run: |
        repo sync -c --no-tags --no-clone-bundle -j$(nproc --all)

    - name: Setup Environment
      run: |
        source build/envsetup.sh
        lunch aosp_poplar-userdebug

    - name: Build ROM
      run: |
        mka bacon -j$(nproc)

    - name: Upload ROM
      uses: actions/upload-artifact@v2
      with:
        name: ROM
        path: out/target/product/poplar/*.zip
